version: 2.1
jobs:
  rsmas_insar testing:
    machine:
      image: ubuntu-2004:202010-01
      environment:
          CONDA_PREFIX: /root/rsmas_insar/tools/miniforge
          RSMASINSAR_HOME: /root/rsmas_insar
      user: root

    working_directory: /root/tools/MintPy
    resource_class: large

    steps:
      - checkout
      - run:
          name: Set up Enviornment
          apt update
          apt-get update --yes && apt-get upgrade --yes
          apt-get install --yes git wget

          cd rsmas_insar/setup
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          bash Miniforge3-Linux-x86_64.sh -b -p ${RSMASINSAR_HOME}/tools/miniforge
          ${RSMASINSAR_HOME}/tools/miniforge/bin/mamba init bash
            # modify/export env var PATH to BASH_ENV to be shared across run steps
          echo 'export PATH=${CONDA_PREFIX}/bin:${PATH}' >> ${BASH_ENV}

          ### Source the environment  #################
          source platforms_defaults.bash;
          source environment.bash;

          # check install
          minsarApp.bash --help

      - run:
          name: download dem
          command: |
            minsarApp.bash /work2/05861/tg851601/stampede2/code/rsmas_insar/samples/unittestGalapagosSenDT128.template --dostep dem

workflows:
  version: 2
