version: 2.1
jobs:
  rsmas-insar-testing:
    machine:
      image: default

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "SHA256:UQXk8EzF60pAQ4fbeZgkWDcI3OMEXV5LcyuK6KJzJy8"
      - run:
          name: Set up Enviornment
          command: |
            echo "Working directory: $PWD"
            bash -x setup/install.bash
            minsar/minsarApp.bash --help

      - run:
          name: Download Dem
          command: |
            export RSMASINSAR_HOME=${CIRCLE_WORKING_DIRECTORY}
            export SCRATCHDIR=${RSMASINSAR_HOME}
            wget http://149.165.154.65/data/circleci/ci_minsarApp_dem.tar
            tar xvf ci_minsarApp_dem.tar

            cd unittestGalapagosSenDT128
            minsar/dem_rsmas.py  ${RSMASINSAR_HOME}/samples/circleci/unittestGalapagosSenDT128.template --ssara_kml
            minsar/minsarApp.bash ${RSMASINSAR_HOME}/samples/circleci/unittestGalapagosSenDT128.template --dostep dem

workflows:
  version: 2
  testing:
    jobs:
      - rsmas-insar-testing
