version: 2.1
jobs:
  rsmas-insar-testing:
    machine:
      image: default

    steps:
      - checkout
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Set up Enviornment
          command: |
            pwd
            ls
            ls setup
            ls setup/install.bash
            ./setup/install.bash
            minsarApp.bash --help

      - run:
          name: Download Dem
          command: |
            export RSMASINSAR_HOME=${CIRCLE_WORKING_DIRECTORY}
            export SCRATCHDIR=${RSMASINSAR_HOME}
            wget http://149.165.154.65/data/circleci/ci_minsarApp_dem.tar
            tar xvf ci_minsarApp_dem.tar

            cd unittestGalapagosSenDT128
            dem_rsmas.py  ${RSMASINSAR_HOME}/samples/circleci/unittestGalapagosSenDT128.template --ssara_kml
            minsarApp.bash ${RSMASINSAR_HOME}/samples/circleci/unittestGalapagosSenDT128.template --dostep dem

workflows:
  version: 2
  testing:
    jobs:
      - rsmas-insar-testing
