version: 2.1
jobs:
  rsmas-insar-testing:
    machine:
      image: default

    steps:
      - checkout
      - run:
          name: Set up Enviornment
          command: |
            pwd
            export RSMASINSAR_HOME=${CIRCLE_WORKING_DIRECTORY}
            export CONDA_PREFIX=${RSMASINSAR_HOME}/tools/miniforge
            cd setup

            miniconda_version=Miniconda3-latest-Linux-x86_64.sh
            if [ "$(uname)" == "Darwin" ]; then miniconda_version=Miniconda3-latest-MacOSX-arm64.sh ; fi
            wget http://repo.continuum.io/miniconda/$miniconda_version --no-check-certificate -O $miniconda_version #; if ($? != 0) exit;
            chmod 755 $miniconda_version
            bash ./$miniconda_version -b -p ../tools/miniconda3

            source platforms_defaults.bash
            source environment.bash
            minsarApp.bash --help

      - run:
          name: Download Dem
          command: |
            pwd
            export RSMASINSAR_HOME=${CIRCLE_WORKING_DIRECTORY}
            source setup/platforms_defaults.bash
            source setup/environment.bash
            pwd
            minsarApp.bash ${RSMASINSAR_HOME}/samples/unittestGalapagosSenDT128.template --dostep dem

workflows:
  version: 2
  testing:
    jobs:
      - rsmas-insar-testing
