version: 2.1
jobs:
  rsmas-insar-testing:
    machine:
      image: default

    steps:
      - checkout
      - run:
          name: Set up Enviornment
          command: |
            export RSMASINSAR_HOME=/root/rsmas_insar
            export CONDA_PREFIX=${RSMASINSAR_HOME}/tools/miniforge
            cd rsmas_insar/setup
            wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
            bash Miniforge3-Linux-x86_64.sh -b -p ${RSMASINSAR_HOME}/tools/miniforge
            ${RSMASINSAR_HOME}/tools/miniforge/bin/mamba init bash
            echo 'export PATH=${CONDA_PREFIX}/bin:${PATH}' >> ${BASH_ENV}
            source platforms_defaults.bash;
            source environment.bash;
            minsarApp.bash --help

      - run:
          name: Download Dem
          command: |
            minsarApp.bash /work2/05861/tg851601/stampede2/code/rsmas_insar/samples/unittestGalapagosSenDT128.template --dostep dem

workflows:
  version: 2
  testing:
    jobs:
      - rsmas-insar-testing
